// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WebServiceFiap.Data.Contexts;

#nullable disable

namespace WebServiceFiap.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260612233914_V1__Cria_Tabela_Usuarios")]
    partial class V1__Cria_Tabela_Usuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebServiceFiap.Models.CatadorItemModel", b =>
                {
                    b.Property<long>("IdCatador")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_catador");

                    b.Property<long>("IdItem")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_item");

                    b.Property<bool>("FoiEntregue")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("foi_entregue");

                    b.HasKey("IdCatador", "IdItem");

                    b.HasIndex("IdItem");

                    b.ToTable("tb_catador_item");
                });

            modelBuilder.Entity("WebServiceFiap.Models.CatadorModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<float>("CapacidadeVolumeTotal")
                        .HasColumnType("BINARY_FLOAT")
                        .HasColumnName("capacidade_volume_total");

                    b.HasKey("Id");

                    b.ToTable("tb_catador");
                });

            modelBuilder.Entity("WebServiceFiap.Models.CentroColetaModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("endereco");

                    b.Property<float>("VolumeItensAtual")
                        .HasColumnType("BINARY_FLOAT")
                        .HasColumnName("volume_itens_atual");

                    b.Property<float>("VolumeItensTotal")
                        .HasColumnType("BINARY_FLOAT")
                        .HasColumnName("volume_itens_total");

                    b.HasKey("Id");

                    b.ToTable("tb_centros_coleta");
                });

            modelBuilder.Entity("WebServiceFiap.Models.ColetaItemModel", b =>
                {
                    b.Property<long>("IdColeta")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_coleta");

                    b.Property<long>("IdItem")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_item");

                    b.HasKey("IdColeta", "IdItem");

                    b.HasIndex("IdItem");

                    b.ToTable("tb_coleta_itens");
                });

            modelBuilder.Entity("WebServiceFiap.Models.ColetaModel", b =>
                {
                    b.Property<long>("IdColeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_coleta");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdColeta"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data");

                    b.Property<bool>("FoiFinalizada")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("foi_finalizada");

                    b.Property<long>("IdCatador")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_catador");

                    b.Property<long>("IdCentro")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_centro");

                    b.Property<long>("IdDescartador")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_descartador");

                    b.HasKey("IdColeta");

                    b.HasIndex("IdCatador");

                    b.HasIndex("IdCentro");

                    b.HasIndex("IdDescartador");

                    b.ToTable("tb_coletas");
                });

            modelBuilder.Entity("WebServiceFiap.Models.DescartadorModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("endereco");

                    b.HasKey("Id");

                    b.ToTable("tb_descartador");
                });

            modelBuilder.Entity("WebServiceFiap.Models.ItemModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.Property<float>("Volume")
                        .HasColumnType("BINARY_FLOAT")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.ToTable("tb_itens");
                });

            modelBuilder.Entity("WebServiceFiap.Models.UsuarioModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("email");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("funcao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.ToTable("tb_usuario");
                });

            modelBuilder.Entity("WebServiceFiap.Models.CatadorItemModel", b =>
                {
                    b.HasOne("WebServiceFiap.Models.CatadorModel", "Catador")
                        .WithMany("CatadorItens")
                        .HasForeignKey("IdCatador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebServiceFiap.Models.ItemModel", "Item")
                        .WithMany("CatadorItens")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catador");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WebServiceFiap.Models.ColetaItemModel", b =>
                {
                    b.HasOne("WebServiceFiap.Models.ColetaModel", "Coleta")
                        .WithMany("ColetaItens")
                        .HasForeignKey("IdColeta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebServiceFiap.Models.ItemModel", "Item")
                        .WithMany("ColetaItens")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coleta");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WebServiceFiap.Models.ColetaModel", b =>
                {
                    b.HasOne("WebServiceFiap.Models.CatadorModel", "Catador")
                        .WithMany("Coletas")
                        .HasForeignKey("IdCatador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebServiceFiap.Models.CentroColetaModel", "CentroColeta")
                        .WithMany("Coletas")
                        .HasForeignKey("IdCentro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebServiceFiap.Models.DescartadorModel", "Descartador")
                        .WithMany("Coletas")
                        .HasForeignKey("IdDescartador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catador");

                    b.Navigation("CentroColeta");

                    b.Navigation("Descartador");
                });

            modelBuilder.Entity("WebServiceFiap.Models.CatadorModel", b =>
                {
                    b.Navigation("CatadorItens");

                    b.Navigation("Coletas");
                });

            modelBuilder.Entity("WebServiceFiap.Models.CentroColetaModel", b =>
                {
                    b.Navigation("Coletas");
                });

            modelBuilder.Entity("WebServiceFiap.Models.ColetaModel", b =>
                {
                    b.Navigation("ColetaItens");
                });

            modelBuilder.Entity("WebServiceFiap.Models.DescartadorModel", b =>
                {
                    b.Navigation("Coletas");
                });

            modelBuilder.Entity("WebServiceFiap.Models.ItemModel", b =>
                {
                    b.Navigation("CatadorItens");

                    b.Navigation("ColetaItens");
                });
#pragma warning restore 612, 618
        }
    }
}
